name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  validator:
    runs-on: ubuntu-latest
    steps:
      - uses: kontrolplane/pull-request-title-validator@v1.3.2
        with:
          types: "doc,dep,fix,feat,setup,test"
